// Mocks generated by Mockito 5.0.15 from annotations
// in class_clean_architecture/test/usercase/create_account_test.dart.
// Do not manually edit this file.

import 'package:class_clean_architecture/academy_bank.dart' as _i2;
import 'package:class_clean_architecture/src/core/repository/person_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakePerson_0 extends _i1.Fake implements _i2.Person {}

/// A class which mocks [PersonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonRepository extends _i1.Mock implements _i3.PersonRepository {
  @override
  String save(_i2.Person? person) =>
      (super.noSuchMethod(Invocation.method(#save, [person]), returnValue: '')
          as String);
  @override
  _i2.Person recovery(String? documentNumber) =>
      (super.noSuchMethod(Invocation.method(#recovery, [documentNumber]),
          returnValue: _FakePerson_0()) as _i2.Person);
  @override
  String toString() => super.toString();
}
